placeSnowInBlock = true
snowGravity = true
snowAlwaysReplaceable = true
snowAccumulationDuringSnowstorm = true
snowAccumulationDuringSnowfall = true
snowAccumulationMaxLayers = 8
thinnerBoundingBox = true
snowMakingIce = true
snowOnIce = true
snowNeverMelt = false
snowMeltsInWarmBiomes = false
snowNaturalMelt = true
snowReduceFallDamage = true
replaceWorldFeature = true
sustainGrassIfLayerMoreThanOne = true
retainOriginalBlocks = false
sneakSnowball = true
